apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tomcatDep
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080